### ISSUE TITLE
1.14 Port checklist

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#246]
**Everyone:** update this as you notice things left to port/fix for 1.14.

- Fix renders
  - [x] Preview Renders
  - [x] Build Renders (They never get called!!!)
  - [x] Construction Block Renders (This is working --Dire)
  - [x] Paste rendering in-world and in the Template manager GUI (PasteToolBufferBuilder fails)
- [x]  Fix Whitelist from crashing the game
- [x] Port Template Manager
- [x] Port guis
- [x] Replace mesh Implementation for rendering paste container level
- [x] Removal of energy for the creative tab icon
- [x] Crafting recipes
- Reference
  - [x] move general purpose constants to `Reference` class (might have missed some somewhere)
  - [x] move NBT-Keys to `NBTKeys` class (might have missed some somewhere)
  - [x] delegate Translations throught to Translation enums

### Implemented fixes to 1.12 that will be missing in 1.14
- [x] [#145] Resolved by adding a button to the Radial Menu to open the Shift Right Click gui (CopyGui, PasteGui)
- [x] [#319] Resolved by added a Dimensional check within the getRemoteInventory method. 
- [x] [#321] Resolved by checking for valid placement before the actual replacement happens. This was done using a hack. I removed the block, check for valid, then placed it back to allow the effect block to handle the rest. This can be done using the FakeWorld in 1.14 instead of doing it in the main world. 
- [x] [#322] Resolved by using `ConnectedSurface.create` instead of recursion.
- [x] [#323] Extending the try catches to stop crashing but does not resolve the main issue. Extensions can be seen here https://github.com/Direwolf20-MC/BuildingGadgets/commit/0de8efe4d33b7135c1041c193a5a391f92c73c45
- [x] [#313] Resolved by rebalancing the durability. Ignore this if we have a charger for the first version of 1.14 mod.

**Comment by MajorTuvok** [comment]
To everyone willing to help:  https://discord.gg/qqUUtu3

**Comment by MajorTuvok** [comment]
@hnOsmium0001 ?

**Comment by hnOsmium0001** [comment]
I think only the issue creator and collaborators (if he chose "Allow edits from collaborators") can edit, or check something.

**Comment by MichaelHillcox** [comment]
This is a public list to show everyone what needs doing. We'll maintain it as PRS are made. Feel free to suggest anything we may have forgotten :p
