### ISSUE TITLE
1.14 - 3.1.0 Master task list

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#397]
Plz add new issues here whilst development so we can fix them before stable. 

## The list
- [ ] You can build when the selection is inside of you allowing you to kill yourself (this is a result of  making effect Blocks TileEntities - previously when they were Entities, they pushed you out)
- [ ] Template Manager and Charging station do not support JEI. Todo: found out why.
- [ ] Replace Destruction gadget gui completely and make it more user friendly and move it off of shift right click. Currently I'm thinking about rendering a 3d outline that the player can move their mouse over and drag to increase and decrease the vector they wish to change. This would also auto cap meaning players don't need to do math in their head for it haha.
- [ ] Remove all gadgets shift right-click functionality and push it all onto a button on the main `g` menu.
- [x] This is a really old bug... When shift right-click you can bypass area size checks by setting an area without already having an area selected. This shouldn't happen. Although the cords mode is logically useful, I think we should disable it / add clearer text to show if you're in cords mode or not and if you're not then the inputs should be disabled. We should also fix the size check bypass(different for in-dev)
- [x] Missing Item Tooltip is offset by one row and as a result renders  the last line outside of the tooltip box

- [ ] Copy paste gadget shows paste render as invalid even with the correct items in the inventory: https://i.imgur.com/XjRk0LE.png
