### ISSUE TITLE
1.12 final todo list

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#402]
This is the final things I'll do for 1.12 unless something I do effects new bugs reported.

- [x] backport #383 
- [x] fix Connected modes using erroneaous Range (can someone explain this please)
- [x] fix #334 - Can't fix, getQuads is broken on mc / xnets side.
- [x] fix #302 
- [x] fix modes using the wrong default size
- [x] check #386
- [x] check #385 
- [x] check #356 
- [x] investigate #373 
- [x] investigate #387 
- [x] backport #284

**Comment by duely** [comment]
I can personally say that #356 is definitely fixed, but you might need to examine adding some sort of try/except check when using the buffer builder to render pre-existing blocks in the event that you run into a block that itself is a baked model using the buffer builder, so that you can bypass the crash (perpetually as you have to modify the NBT manually via NBT Explorer) it causes and say something like "this block isn't compatible".

**Comment by MichaelHillcox** [comment]
@duely I don't think it would be fixed as we've done no work to fix it although I can say for sure that it's only effecting a small % of people and can accept that they likely have the resources to quickly wip up another ME system and use that in preference of the full one.

As for the rest, I'm not 100% sure on what you're referring to. If it's #334 then I'm actually not sure what to do about it and would love some input. My main problem is that the throw happens quite deep into the code on a `getQuads` method, I've attempted to verify the values of these methods but they still lead to a crash. Simply wrapping a try catch causes other issues as the build buffer has already been submitted to but it crashes / throws before that buffer has been closed.

**Comment by MichaelHillcox** [comment]
Closed as off https://github.com/Direwolf20-MC/BuildingGadgets/releases/tag/2.7.4-1.12.x

**Comment by duely** [comment]
My bad, I typed the wrong issue. I was specifically referring to the one with Mystical World/Mystical Lib. My point still stands that it would be a good idea to wrap your sub-calls to build blocks while inside a buffer builder to avoid crashing and then inability to reopen the save without modifying the player's inventory data.
