### ISSUE TITLE
Feature request master list

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#534]
(todo: automate this list)

## Note
Just because an issue is in this list does not mean that it will be implemented. I've compressed our feature requests into a single issue to clean up our project issues to make bugs and other information easier to find.

## Feature requests
- [ ] #505 Suggestion - Paste Gadget Anchor
- [ ] #500 Improve template manager Gui (Template manager UI unclear) `Confimed for rewrite + 1.16.4`
- [ ] #499 Savable presets for gadget settings
- [ ] #498 One time use Gadgets for modpacks
- [ ] #497 Replace construction paste with actual block on right-click `Confirmed for rewrite`
- [ ] #496 Corner selecting `Confirmed for rewrite`
- [ ] #495 Block replacement in templates `confirmed for rewrite + feature version`
- [ ] #493 Having a small list of pre-build templates for the copy paste gadget `confirmed for rewrite`
- [ ] #489 A library function for the Copy-paste gadget `same as above?`
- [ ] #477 Extended support for Block-Providing Items `Confirmed for rewrite and PR's`
- [ ] #449 Cutting Gadget `Confirmed for rewrite`
- [ ] #447 Curve mode `might implement`
- [ ] #444 Pin the Material list to the overlay `Confirmed`
- [ ] #421 [Suggestion] Circular walls based on diameter or radius `might implement`
- [ ] #409 compatibility with Cubic chunks `might implement`
- [ ] #391 Add tapemeasure like C&B
- [ ] #374 Combine Destruction Gadget's Shift+Right-click settings into the Radial Menu? `Confirmed for rewrite`
- [ ] #366 Randomized patterns `Confirmed for rewrite`
- [ ] #365 Offset for destruction- and building-gadget `Confirmed for all gadgets`
- [ ] #353 Allow Placeholder Blocks to be loaded instead of missing Blocks
- [ ] #305 At least 2 rotation axes for all Gadgets `might implement`
- [ ] #303 Allow configurable behaviour, for paste vs block preference
- [ ] #255 [Feature Request] Provide pre-made in modpacks (same as #498 / #493 / #489)
- [ ] #178 Structure preview stays
