### ISSUE TITLE
Legacy issues for PR's

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#535]
I've compiled a list of issues that are still open and need resolving. If you feel like working with 1.12 then please consider making a PR to resolve some of these issues :+1:

## `1.14` - Issues
- [ ] [Unresolved] #430 Copy and Paste tool, not copying right information
- [ ] [Unresolved] #406 additional keybinds dont work

## `1.12` - Issues
- [ ] [Unresolved] #422 AE2 Networks and Copy-Paste gadget Kills the TPS. 
- [ ] [Unresolved] #474 Undoing with Copy Paste Gadget gives me a different block than was placed
- [ ] [Unresolved] #503 [1.12.2] Dupe bug with BiomesOPlenty
- [ ] [Unresolved] #506 Paste Gadget cannot clear settings 
- [ ] [Unresolved] #509 Undo not compatible with dropt
